public class CommonsConstants {
  //Account Validation Status
  public static final String ACC_VALIDATION_STATUS_VALIDATED = 'Validated';
  public static final String ACC_VALIDATION_STATUS_PENDING = 'Pending';
  public static final String ACC_VALIDATION_STATUS_READY_FOR_REVIEW = 'Ready For Review';

  //Account Record Types
  public static final String ACCOUNT_RECORD_TYPE_1 = 'Customer';
  public static final String ACCOUNT_RECORD_TYPE_2 = 'Partner';
  public static final String ACCOUNT_RECORD_TYPE_3 = 'Partner Prospect';
  public static final String ACCOUNT_RECORD_TYPE_4 = 'Technology Alliance';

  //Account Sync Status
  public static final String ACC_SYNC_STATUS_VALID = 'Valid';
  public static final String ACC_SYNC_STATUS_NOT_VALID = 'Not Valid';
  public static final String ACC_SYNC_STATUS_PENDING = 'Pending';
  public static final String ACC_SYNC_STATUS_SYNCED = 'Synced';
  public static final String ACC_SYNC_STATUS_ERROR = 'Error';
  public static final String ACC_SYNC_STATUS_DO_NOT_SYNC = 'Do Not Sync';

  public static final String ACC_UIPATH_SF_CONNECTOR_TEMPLATE = 'Account Integration';
  public static final String ADD_UIPATH_SF_CONNECTOR_TEMPLATE = 'Address Integration';
  public static final String ACC_RDC_UIPATH_SF_CONNECTOR_TEMPLATE = 'COE5101_Account_CustomersScreening';

  /********** Address Constants ***********/
  // Address Record Types
  public static final String ADDRESS_RECORD_TYPE_LOCKDOWN = 'Lockdown';

  //Address Validation Status
  public static final String ADD_VALIDATION_STATUS_VALIDATED = 'Validated';
  public static final String ADD_VALIDATION_STATUS_PENDING = 'Pending';
  public static final String ADD_VALIDATION_STATUS_READ_YFOR_REVIEW = 'Ready For Review';

  // Address Sync Status
  public static final String ADD_SYNC_STATUS_VALID = 'Valid';
  public static final String ADD_SYNC_STATUS_NOT_VALID = 'Not Valid';
  public static final String ADD_SYNC_STATUS_PENDING = 'Pending';
  public static final String ADD_SYNC_STATUS_SYNCED = 'Synced';
  public static final String ADD_SYNC_STATUS_ERROR = 'Error';
  public static final String ADD_SYNC_STATUS_DO_NOT_SYNC = 'Do Not Sync';

  // User Profiles
  public static final String LEGAL_USER_PROFILE = 'Legal User';
  public static final String EXEC_USER_PROFILE = 'Executive';
  public static final String STANDARD_USER_PROFILE = 'Standard User';
  public static final String DATA_STEWARD_PROFILE = 'Data Stewards';
  public static final String SUPER_ADMIN_PROFILE = 'Super Admin';
  public static final String INTEGRATION_USER_PROFILE = 'Integration User';
  public static final String SYS_ADMIN_PROFILE = 'System Administrator';
  public static final String GEO_LEADS_PROFILE = 'Sales Ops Geo Leads';

  //Integration Constants
  public static final String INTEGRATION_FIELDSET_NAME = 'Boomi_Integration_Field_Set';
  public static final String INTEGRATION_FIELDSET_NAME_TEST = 'Boomi_Integration_Field_Set_No_Deps';
  public static final String INTEGRATION_SYNC_STATUS_FIELD = 'Sync_Status__c';
  public static final String INTEGRATION_PROFILE_NAME = 'Integration User';

  public static final String BOOMI_INTEGRATION_PERMISSION_SET_NAME = 'DellBoomiIntegrationUser';
}
